### ISSUE TITLE
启动失败？

### ISSUE THREAD

**Issue by dpc761218914** [k-water/egg-blog#1]
博主，你好，安装依赖后，项目启动失败，mysql需要初始化吗

**Comment by dpc761218914** [comment]
2018-07-14 21:21:37,457 ERROR 6176 nodejs.SequelizeConnectionError: Unknown data
    at Utils.Promise.tap.then.catch.err (E:\githubProject\egg-blog\node_modules\
From previous event:
    at ConnectionManager.connect (E:\githubProject\egg-blog\node_modules\sequeli
    at sequelize.runHooks.then (E:\githubProject\egg-blog\node_modules\sequelize
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at ConnectionManager._connect (E:\githubProject\egg-blog\node_modules\sequel
    at ConnectionManager.getConnection (E:\githubProject\egg-blog\node_modules\s
    at Promise.try (E:\githubProject\egg-blog\node_modules\sequelize\lib\sequeli
From previous event:
    at Promise.resolve.retryParameters (E:\githubProject\egg-blog\node_modules\s
    at E:\githubProject\egg-blog\node_modules\retry-as-promised\index.js:39:21
    at retryAsPromised (E:\githubProject\egg-blog\node_modules\retry-as-promised

**Comment by k-water** [comment]
应该是依赖没安装好，在重新安装下，要先建一个名为`egg_db`的数据库

**Comment by dpc761218914** [comment]
非常感谢，需要先在mysql中新建egg_db~~

**Comment by dpc761218914** [comment]
感谢指导
